require_relative '../lib/dot_net_framework'
require_relative '../lib/dot_net_framework_command'

DotNetFramework.installations.each do |dot_net_framework|
  command = DotNetFrameworkCommand.new dot_net_framework, 'aspnet_compiler.exe'
  next unless command.exists?

  version = dot_net_framework.major_version + dot_net_framework.minor_version
  task_name = "#{command.command_name_without_extension}_#{version}"
  output_dir = File.expand_path task_name
  directory output_dir

  task_desc = "Generate reference for #{command.command_name} #{dot_net_framework.version}."
  desc task_desc
  task task_name => [output_dir] do
    print "#{task_desc}..".sub('Generate', 'Generating')
    command.execute %Q[-? > "#{output_dir}/help.txt"]
    puts ' done'
  end

  task :default => [task_name]
end